import Header from "../components/Header";
import Footer from "../components/Footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "ToolCraftKit terms of service. Rules and guidelines for using our free online tools.",
};

export default function Page() {
  const s = {
    page: { maxWidth: 720, margin: "0 auto", padding: "32px 20px 60px" } as const,
    h1: { fontSize: 28, fontWeight: 700, color: "#1C1917", marginBottom: 4 } as const,
    sub: { fontSize: 14, color: "#78716C", marginBottom: 32 } as const,
    h2: { fontSize: 18, fontWeight: 600, color: "#1C1917", marginTop: 32, marginBottom: 8 } as const,
    p: { fontSize: 14, color: "#57534E", lineHeight: 1.8, marginBottom: 12 } as const,
  };

  return (
    <>
      <Header />
      <main style={s.page}>
        <h1 style={s.h1}>Terms of Service</h1>
        <p style={s.sub}>Last updated: August 2026</p>

        <p style={s.p}>By accessing and using ToolCraftKit (toolcraftkit.com), you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, please do not use our website.</p>

        <h2 style={s.h2}>Use of Services</h2>
        <p style={s.p}>ToolCraftKit provides free online tools for text processing, calculations, conversions, code formatting, and other utility purposes. All tools are provided &quot;as is&quot; and are intended for general informational and utility purposes only. You may use our tools for personal and commercial purposes without restriction.</p>

        <h2 style={s.h2}>No Warranty</h2>
        <p style={s.p}>While we strive for accuracy, we make no warranties or guarantees about the accuracy, reliability, completeness, or suitability of the results produced by our tools. Financial calculators (loan, ROI, discount) provide estimates only and should not be used as the sole basis for financial decisions. Always consult qualified professionals for important financial, legal, or medical decisions.</p>

        <h2 style={s.h2}>Privacy and Data</h2>
        <p style={s.p}>All tools run entirely in your browser. We do not collect, store, or transmit any data you enter into our tools. For more details, please see our Privacy Policy.</p>

        <h2 style={s.h2}>Intellectual Property</h2>
        <p style={s.p}>The content, design, and code of ToolCraftKit are protected by copyright. You may not copy, reproduce, distribute, or create derivative works based on our website without prior written permission. The results and outputs generated by our tools (QR codes, invoices, formatted text, etc.) are yours to use freely.</p>

        <h2 style={s.h2}>Advertisements</h2>
        <p style={s.p}>ToolCraftKit displays advertisements through Google AdSense to support the free operation of our tools. We do not control the content of third-party advertisements. If you encounter an inappropriate ad, please report it to Google directly.</p>

        <h2 style={s.h2}>Limitation of Liability</h2>
        <p style={s.p}>To the maximum extent permitted by law, ToolCraftKit and its operators shall not be liable for any direct, indirect, incidental, consequential, or special damages arising from your use of or inability to use our tools or website. This includes but is not limited to damages for loss of profits, data, or other intangible losses.</p>

        <h2 style={s.h2}>Modifications</h2>
        <p style={s.p}>We reserve the right to modify, suspend, or discontinue any part of our website or tools at any time without notice. We may also update these Terms of Service at any time. Continued use of the website after changes constitutes acceptance of the updated terms.</p>

        <h2 style={s.h2}>Governing Law</h2>
        <p style={s.p}>These terms are governed by and construed in accordance with the laws of British Columbia, Canada. Any disputes arising from these terms or your use of the website shall be subject to the exclusive jurisdiction of the courts of British Columbia.</p>

        <h2 style={s.h2}>Contact</h2>
        <p style={s.p}>For questions about these terms, contact us at: legal@toolcraftkit.com</p>
      </main>
      <div style={{ maxWidth: 720, margin: "0 auto", padding: "0 20px" }}><Footer /></div>
    </>
  );
}
